imports:
    - { resource: phpbb_tables.yml }
    - { resource: ud_constants.yml }

services:
    david63.userdefaults.listener:
        class: david63\userdefaults\event\listener
        arguments:
            - '@config'
            - '%udconstants%'
        tags:
            - { name: event.listener }

    david63.userdefaults.admin.controller:
        class: david63\userdefaults\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@language'
            - '@dbal.conn'
            - '@david63.userdefaults.core.functions'
            - '%tables%'
            - '%udconstants%'

    david63.userdefaults.core.functions:
        class: david63\userdefaults\core\functions
        arguments:
            - '@ext.manager'
