parameters:
    udconstants:
        form_key: 'user_defaults'

        notification: 0
        email: 1

        viewimg: 0
        viewflash: 1
        viewsmilies: 2
        viewsigs: 3
        viewavatars: 4
        viewcensors: 5
        attachsig: 6
        bbcode: 8
        smilies: 9
